name: pixelsand
description: Web site pixelsand.online
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  loggable: ^1.0.1
  nucleoid: ^0.2.0
dev_dependencies:
  pedantic: ^1.8.0

nucleoid:
  assets:
    - assets/favicon.ico
    - assets/images

#dependency_overrides:
#  nucleoid:
#    path: ../dart-nucleoid-main/nucleoid